FROM jdxcode/mise:latest AS builder

RUN apt-get update && apt-get install -y libsqlite3-dev && rm -rf /var/lib/apt/lists/*
RUN git config --global --add safe.directory '*'

WORKDIR /app
COPY mise.toml mise.lock ./

ENV MISE_YES=1
ENV MISE_DATA_DIR=/home/flutter/.local/share/mise
ENV MISE_CACHE_DIR=/home/flutter/.cache/mise
RUN mise trust
RUN mise install flutter

COPY pubspec.yaml pubspec.lock ./
COPY packages ./packages

RUN mise exec flutter -- flutter pub get
RUN mise exec flutter -- dart compile exe packages/server/bin/server.dart -o server

FROM ubuntu:24.04 AS runner
WORKDIR /app

RUN apt-get update && apt-get install -y libssl-dev ca-certificates sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/server server

CMD [ "/app/server" ]
