[tools]
codex = "0.104.0"
flutter = "3.38.9-stable"
helix = "25.07.1"
jj = "0.38.0"

[tasks.web]
description = "Run debug on the web"
run = "cd packages/app && flutter run -d chrome --dart-define=API_URL=http://localhost:8080"
